---
- name: ensure old docker versions are not hanging around
  apt:
    name: [docker, docker-engine, docker.io]
    state: absent
  tags:
    - docker
    - apt

- name: ensure required packages are present
  apt:
    name: "{{ _dubzland_docker_prerequisites }}"
    state: present
  tags:
    - docker
    - apt

- name: ensure the docker gpg key is present
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker
    - apt

- name: ensure the docker repository is present
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb['codename'] }} stable"
    state: present
    update_cache: yes
  tags:
    - docker
    - apt

- name: ensure docker is installed
  apt:
    name: docker-ce={{ dubzland_docker_version }}
    state: present
  tags:
    - docker
    - apt

- name: ensure docker-compose is installed
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ _dubzland_docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  tags:
    - docker
